# Generated by Django 6.0.1 on 2026-02-09 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('redirect_url', models.URLField(blank=True, max_length=1000)),
                ('salary', models.CharField(blank=True, max_length=200)),
                ('posted_date', models.CharField(blank=True, max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'job_id')},
            },
        ),
    ]
